### ISSUE TITLE
Comparisson of Legacy Blinding vs TXPipe Blindnig

### ISSUE THREAD

**Issue by arthurmloureiro** [LSSTDESC/Blinding#7]
This issue will track comparisons between the legacy Cosmosis and the current TXPipe blinding implementations.

## Questions
- Can TXPipe blind a data-vector directly or only blind a data-vector from applying estimators to a catalogue?
- Can cosmosis output in SACC format? Relevant to #6 too.

## Tasks
- [ ] Output a fiducial data-vector from DESC pipelines
- [ ] Compare fiducial cosmology data-vectors between TXPipe (maybe firecrown?) and Cosmosis v2
- [ ] Compare blinding ratios between both approaches
- [ ] Investigate discrepancies 

Cc: @jablazek @jessmuir
